application: thoughts-journal
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /images
  static_dir: images
- url: /.*
  script: thoughtsjournal.app

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: latest
